name: Frontend E2E Tests

on:
  push:
  pull_request:
    branches:
      - "develop"
      - "test/gitflows"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install Cypress dependencies
        run: npx cypress install

      - name: Run Server
        run: npm run dev &

      - name: Wait for Server
        run: npx wait-on http://localhost:5173

      - name: Run Cypress
        run: npx cypress run