name: Python Linter

on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed

permissions:
  contents: write

jobs:
  lint:
    if: > 
      github.event.workflow_run.conclusion == 'success' && 
      contains(fromJson('["develop", "test/gitflows"]'), github.event.workflow_run.head_branch)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 autoflake flake8 isort

      - name: Auto-format with autopep8
        run: |
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive --exclude venv,__pycache__ .
          autopep8 --in-place --recursive --aggressive --exclude venv,__pycache__ .
          isort --profile black .

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin ${{ github.event.workflow_run.head_branch }}  
          git checkout ${{ github.event.workflow_run.head_branch }}      
          git pull --rebase origin ${{ github.event.workflow_run.head_branch }} || echo "No remote changes to rebase"
          git add .
          git diff --cached --quiet || (git commit -m "style: run linter" && git push origin HEAD:${{ github.event.workflow_run.head_branch }})

      - name: Lint with flake8
        run: flake8 --config=.flake8 .