name: Python Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Auto-format with autopep8
        run: |
          autoflake --in-place --remove-all-unused-imports --recursive --exclude venv,__pycache__ .
          autopep8 --in-place --recursive --aggressive --exclude venv,__pycache__ .

      - name: Lint with flake8
        run: flake8 --config=.flake8 .